Capitulo2 exercicios
MarceloHadad/PrincipiosEPraticasDeProgramacaoComCpp pull request #3
Opened 2022-03-27 22:51 UTC by MarceloHadad

2022-03-28 02:19 UTC, janaina-campos reviewed
Falta ignorar os arquivos do Visual Studio

2022-03-28 02:23 UTC, janaina-campos commented on oi_mundo/oi_mundo.cpp
> +int main() // O programa C++ inicia executando a fun��o main
Corrigir encoding do comentário.

2022-03-28 02:32 UTC, janaina-campos requested changes

2022-03-28 02:32 UTC, janaina-campos commented on oi_mundo/oi_mundo.cpp
> +int main() // O programa C++ inicia executando a fun��o main
Corrigir encoding do comentário.

2022-03-28 02:32 UTC, janaina-campos commented on instructions/std_lib_facilities.h
> +std_lib_facilities.h
Deixar a std_lib na raiz do projeto e os projetos filho devem procurar a lib na raiz.

2022-03-28 02:32 UTC, janaina-campos commented on instructions/instructions.cpp
> +    cout << "Se você estiver sentado em uma cadeira, levante da cadeira\n";
Onde esta a cadeira? Precisa informar o local para ser mais coerente

2022-03-28 02:32 UTC, janaina-campos commented on .gitignore
> +CMakeCache.txt
Falta ignorar os arquivos do Visual Studio

2022-03-28 16:33 UTC, MarceloHadad commented
> Falta ignorar os arquivos do Visual Studio

A mensagem do commit foi errada, isso já foi feito no https://github.com/MarceloHadad/PrincipiosEPraticasDeProgramacaoComCpp/commit/b1e5f0f0e29e1f88944be2a1861811689949fa89

2022-03-29 03:01 UTC, janaina-campos approved these changes

2022-03-29 03:02 UTC, merged